### ISSUE TITLE
Balance Options

### ISSUE THREAD

**Issue by DanShu15** [Draylar/fabric-furnaces#18] opened 2020-06-17 02:39 UTC
We're using 1.15.2pre4-1.20
I was wondering if a config option to disable the dupe feature on the later furnaces would be possible?
I love the furnaces, and I see the increased speed vs consumption as a great feature I'd like to keep on our server.
I don't see a way for me to disable the dupe chance, unfortunately, and with grinders an easy dupe loop of grinding an ore then running it through the later furnaces presents itself.
This leaves me with only the choice of disabling the recipes for the later furnaces, but I'd love to keep them if it would be possible.
Thanks for all your great mods!

**Comment by Draylar** [comment] 2020-06-29 03:13
I added a config for adding/modifying furnaces in 1.3.0  (1.16.1, [GH](https://github.com/Draylar/fabric-furnaces/releases/tag/1.16.1-1.3.0), [CF](https://www.curseforge.com/minecraft/mc-mods/fabric-furnaces/files/2991725)). You *can't* use this to tell the client what Furnaces to add, but it should work for configuring speed/fuel/dupe given that those properties only take effect on the server. You can find the config file at `fabric-furnaces.json5`. Let me know if anything goes wrong!

**Comment by HumanMint** [comment] 2020-12-28 02:07
I noticed that the fabric furnaces that were already placed in the world while the dupe chance was enabled still retain the same dupe chance even after updating the config file and restarting the server/world. Newly placed fabric furnaces that supposedly had their dupe chances removed work properly as intended while the fabric furnaces that already existed in the world before adjusting the config still dupes the items with the previous dupe settings. Is this intended?

**Comment by Draylar** [comment] 2021-01-02 02:27
Fixed in 1.3.3, thanks for letting me know.

**Closed as completed by Draylar** 2021-01-02 02:27 UTC
Labels: bug
